# Generated by Django 2.2.5 on 2019-10-20 09:08

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('name', models.TextField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('name', models.TextField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('login', models.CharField(max_length=30, primary_key=True, serialize=False, unique=True)),
                ('password', models.TextField()),
                ('fname', models.CharField(max_length=30, null=True)),
                ('lname', models.CharField(max_length=30, null=True)),
                ('patronymic', models.CharField(max_length=30, null=True)),
                ('birthday', models.DateField(null=True)),
                ('date_registration', models.DateField(auto_now_add=True)),
                ('date_visit', models.DateField()),
                ('uuid_avatar', models.UUIDField(default=uuid.uuid4, null=True, unique=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.Group')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceObject',
            fields=[
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='system.Service')),
                ('object_type', models.CharField(max_length=50)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
            ],
            options={
                'unique_together': {('service', 'object_type')},
            },
        ),
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.TextField(unique=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.User')),
            ],
        ),
        migrations.CreateModel(
            name='UserPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.Permission')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.User')),
                ('object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.ServiceObject')),
            ],
        ),
        migrations.CreateModel(
            name='GroupPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.Group')),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.Permission')),
                ('object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.ServiceObject')),
            ],
        ),
    ]
