# Generated by Django 2.2.5 on 2019-11-02 14:32

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('text', models.TextField()),
                ('user_uuid', models.UUIDField(default=uuid.uuid4)),
                ('rating', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('tag', models.CharField(max_length=30, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='TagsForQuestions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.Question')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.Tag')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('author_uuid', models.UUIDField(default=uuid.uuid4)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.Question')),
            ],
        ),
        migrations.CreateModel(
            name='FilesForQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_uuid', models.UUIDField(default=uuid.uuid4)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.Question')),
            ],
            options={
                'unique_together': {('question', 'file_uuid')},
            },
        ),
        migrations.CreateModel(
            name='FilesForAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_uuid', models.UUIDField(default=uuid.uuid4)),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.Answer')),
            ],
            options={
                'unique_together': {('answer', 'file_uuid')},
            },
        ),
    ]
